name: Deploy Lambda Function

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Package the Lambda function
      - name: Package Lambda function
        run: |
          mkdir package
          pip install -r requirements.txt --target ./package
          cp lambda_function.py ./package/
          cd package && zip -r ../function.zip . && cd ..

      # Step 5: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          function-name: github-analytics-dashboard
          zip-file: function.zip